export const applications = [
  {
    id: "health-education",
    category: "Health & anatomy",
    title: "An anatomy illustration becomes a health explainer.",
    shortTitle: "Health education",
    summary: "A clear focal image, a short message and room for your own teaching notes.",
    audience: "Health educators, course creators and communication teams.",
    brief: "Introduce a body system to a general audience without overwhelming the page with specialist detail.",
    approach: "Use one anatomical illustration as the focal point. Set a clear reading order with a large title, a short introduction and separate, editable notes. Adapt the vocabulary and annotations to the audience, with subject review before publication.",
    deliverables: "An illustrated handout, a presentation slide and a social-format adaptation, with text kept editable.",
    projectType: "Health communication",
    channel: "Health education handout, presentation or social content",
    resourceSlug: "anatomical-heart-illustration",
    resourceLabel: "Get the free heart illustration",
    resourceHref: "/resources/anatomical-heart-illustration/",
  },
  {
    id: "plant-biology-lesson",
    category: "Education & nature",
    title: "A chloroplast cutaway becomes a lesson visual.",
    shortTitle: "Learning materials",
    summary: "An illustration-led lesson opener with space to observe, label and discuss.",
    audience: "Teachers, educational publishers and online learning teams.",
    brief: "Create a visual starting point for a plant biology lesson that works on a classroom screen and in a handout.",
    approach: "Keep the cutaway large enough to discuss. Put learning prompts beside the artwork so the image stays reusable. Build an unlabelled activity version and a reviewed teaching version with terminology appropriate to the class.",
    deliverables: "A lesson slide, a printable observation sheet and a labelled teaching version prepared for your curriculum.",
    projectType: "Education & learning materials",
    channel: "Classroom slides, worksheets or online course",
    resourceSlug: "chloroplast-cutaway-illustration",
    resourceLabel: "Get the free chloroplast illustration",
    resourceHref: "/resources/chloroplast-cutaway-illustration/",
  },
  {
    id: "environmental-technology",
    category: "Environment & technology",
    title: "A technical idea becomes a project story.",
    shortTitle: "Product & project stories",
    summary: "Connect a process illustration with a report and a digital presentation.",
    audience: "Environmental technology companies, project teams and public engagement organisations.",
    brief: "Explain a water-treatment project to partners who need both an accessible overview and a route into the evidence.",
    approach: "Organise the story around the problem, the process and the evidence supplied by the team. Use a consistent visual language across the report and digital presentation, with sources beside any performance claims.",
    deliverables: "A process infographic, a report layout and a project microsite shaped around your verified project information.",
    projectType: "Product & technology communication",
    channel: "Product website, project report or partner presentation",
    resourceSlug: "",
    resourceLabel: "Explore related illustration work",
    resourceHref: "/portfolio/explain/",
  },
] as const;

export type ApplicationId = (typeof applications)[number]["id"];
export const applicationContactUrl = (id: ApplicationId) => `/?application=${id}#contact`;
