export const applications = [
  {
    id: "health-education",
    category: "Health & anatomy",
    title: "Health education poster: understanding skin.",
    shortTitle: "Health education poster",
    summary: "A finished poster combining a skin cutaway, clear labels and an accessible reading order.",
    audience: "Health educators, course creators and communication teams.",
    brief: "Explain skin structure to a general audience in a poster suitable for a health education setting.",
    approach: "Build the poster around a simplified skin cutaway, with a small number of labels and supporting details. Use typography, colour and spacing to guide readers from the overview to the individual layers. Final anatomical content is reviewed against the supplied source material.",
    deliverables: "An illustrated poster, a printable handout and a presentation adaptation, with text kept editable.",
    projectType: "Health communication",
    channel: "Health education handout, presentation or social content",
    resourceSlug: "anatomical-heart-illustration",
    resourceLabel: "Browse health illustration assets",
    resourceHref: "/resources/?topic=Health%20%26%20Anatomy",
  },
  {
    id: "plant-biology-lesson",
    category: "Education & nature",
    title: "Plant biology lesson: from seed to seedling.",
    shortTitle: "Plant biology lesson",
    summary: "A complete lesson slide with a visual sequence, stage labels and a classroom discussion prompt.",
    audience: "Teachers, educational publishers and online learning teams.",
    brief: "Help learners follow seed germination through a clear sequence that works on a classroom screen and in a printed lesson.",
    approach: "Illustrate successive stages with consistent scale, viewpoint and colours. Place short stage labels beside the sequence and close with an observation question. Develop the language and learning tasks around the age group and curriculum.",
    deliverables: "A lesson slide, a printable observation sheet and a labelled teaching version prepared for your curriculum.",
    projectType: "Education & learning materials",
    channel: "Classroom slides, worksheets or online course",
    resourceSlug: "chloroplast-cutaway-illustration",
    resourceLabel: "Browse plant illustration assets",
    resourceHref: "/resources/?topic=Plants%20%26%20Nature",
  },
  {
    id: "environmental-technology",
    category: "Environment & technology",
    title: "Technical project report: a filtration system.",
    shortTitle: "Technical project report",
    summary: "A designed report spread connecting a system cutaway with a concise process diagram.",
    audience: "Environmental technology companies, project teams and public engagement organisations.",
    brief: "Introduce a filtration system to partners who need to understand its components and the route through the process.",
    approach: "Pair a system cutaway with a simple intake-to-outlet sequence. Use consistent component colours and concise labels across the spread. For a commissioned report, develop the drawings from the actual engineering information and support any performance claims with project evidence.",
    deliverables: "A process infographic, a report layout and a project microsite shaped around your verified project information.",
    projectType: "Product & technology communication",
    channel: "Product website, project report or partner presentation",
    resourceSlug: "",
    resourceLabel: "Explore related illustration work",
    resourceHref: "/portfolio/explain/",
  },
] as const;

export type ApplicationId = (typeof applications)[number]["id"];
export const applicationContactUrl = (id: ApplicationId) => `/?application=${id}#contact`;
